# Generated by Django 5.2.6 on 2025-09-22 16:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace', '0004_remove_listing_price_alter_listing_description_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Feedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('feedback_type', models.CharField(choices=[('amelioration', 'Point d’amélioration'), ('commentaire', 'Commentaire général'), ('autre', 'Autre')], max_length=50)),
                ('message', models.TextField()),
                ('date_created', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
