# Generated by Django 5.2.6 on 2025-10-15 01:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace', '0006_feedback_consent_given_feedback_is_approved_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='feedback',
            old_name='date_created',
            new_name='created_at',
        ),
        migrations.RemoveField(
            model_name='feedback',
            name='message',
        ),
        migrations.AlterField(
            model_name='feedback',
            name='feedback_type',
            field=models.TextField(),
        ),
    ]
