# Generated by Django 5.2.6 on 2025-10-15 02:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace', '0007_rename_date_created_feedback_created_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='feedback',
            name='message',
            field=models.TextField(default='message vide'),
            preserve_default=False,
        ),
    ]
