# Generated by Django 5.2.6 on 2025-12-09 21:41
from django.db import migrations
import cloudinary.models

class Migration(migrations.Migration):

    dependencies = [
        ('marketplace', '0011_remove_listing_ownership_check'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listing',
            name='image',
            field=cloudinary.models.CloudinaryField('image', folder='photocards'),
        ),
    ]