# Generated by Django 5.2.6 on 2025-11-14 21:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace', '0008_feedback_message'),
    ]

    operations = [
        migrations.CreateModel(
            name='Photocard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='photocards/')),
                ('consent_given', models.BooleanField(default=False)),
                ('consent_date', models.DateTimeField(auto_now_add=True)),
                ('user_ip', models.GenericIPAddressField(blank=True, null=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='feedback',
            name='feedback_type',
        ),
        migrations.RemoveField(
            model_name='listing',
            name='group',
        ),
        migrations.RemoveField(
            model_name='listing',
            name='member',
        ),
        migrations.RemoveField(
            model_name='listing',
            name='title',
        ),
        migrations.AddField(
            model_name='listing',
            name='groupe',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Groupe/Group'),
        ),
        migrations.AddField(
            model_name='listing',
            name='membre',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Membre/Member'),
        ),
        migrations.AddField(
            model_name='listing',
            name='titre',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Titre/Title'),
        ),
        migrations.AlterField(
            model_name='listing',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='Description'),
        ),
        migrations.AlterField(
            model_name='listing',
            name='image',
            field=models.ImageField(upload_to='listings/', verbose_name='Image'),
        ),
        migrations.AlterField(
            model_name='listing',
            name='is_approved',
            field=models.BooleanField(default=False, verbose_name='Approved'),
        ),
    ]
