# Generated by Django 5.2.6 on 2025-12-04 01:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace', '0010_listing_consent_given_listing_ownership_check_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='listing',
            name='ownership_check',
        ),
    ]
